// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbCfDrWjQybjHL3WjuOg4QF-yqPdF9xew',
    appId: '1:419797598103:web:ea0d82539f4355c513ced2',
    messagingSenderId: '419797598103',
    projectId: 'milcko-a5c94',
    authDomain: 'milcko-a5c94.firebaseapp.com',
    storageBucket: 'milcko-a5c94.appspot.com',
    measurementId: 'G-BET5J9H0W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsg7GCA9mmb48h4d7qir-JtK9-304Po4k',
    appId: '1:419797598103:android:93861b161121e7bc13ced2',
    messagingSenderId: '419797598103',
    projectId: 'milcko-a5c94',
    storageBucket: 'milcko-a5c94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz4h5gNqPNr5hJvG__gW5dJQq0Ys3VJlE',
    appId: '1:419797598103:ios:18be6c528430858813ced2',
    messagingSenderId: '419797598103',
    projectId: 'milcko-a5c94',
    storageBucket: 'milcko-a5c94.appspot.com',
    iosBundleId: 'com.example.milcko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz4h5gNqPNr5hJvG__gW5dJQq0Ys3VJlE',
    appId: '1:419797598103:ios:e1c9a3b0eeb910fc13ced2',
    messagingSenderId: '419797598103',
    projectId: 'milcko-a5c94',
    storageBucket: 'milcko-a5c94.appspot.com',
    iosBundleId: 'com.example.milcko.RunnerTests',
  );
}
